name: Action on push to latest
on: push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: List dir content
        id: list-dcurrent-dir
        run: |
          ls -al ./
          echo ${PWD}

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed ${PWD})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --all --chart-dirs ${PWD}

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install


  # HexF-lint-test:
  #   name: Lint helm chart
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1

  #     - name: Run chart-testing (lint)
  #       id: lint
  #       uses: HexF/chart-testing-action@v3.0.0
  #       with:
  #         command: lint
  #         config: ./ct.yaml

      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.0.0-alpha.3
      #   with:
      #     install_local_path_provisioner: true
      #   # Only build a kind cluster if there are chart changes to test.
      #   if: steps.lint.outputs.changed == 'true'

      # - name: Run chart-testing (install)
      #   uses: HexF/chart-testing-action@v3.0.0
      #   with:
      #     command: install



    # steps:
    #   - uses: actions/checkout@v1
    #   - uses: ./action-a
    #     with:
    #       MY_NAME: "Mona v${GITHUB_REF##*/}"