name: Action on push to latest
on: push

jobs:
  lint-test:
    name: Lint helm chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run chart-testing (lint)
        id: lint
        uses: HexF/chart-testing-action@v3.0.0
        with:
          command: lint
          config: ./ct.yaml

      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.0.0-alpha.3
      #   with:
      #     install_local_path_provisioner: true
      #   # Only build a kind cluster if there are chart changes to test.
      #   if: steps.lint.outputs.changed == 'true'

      # - name: Run chart-testing (install)
      #   uses: HexF/chart-testing-action@v3.0.0
      #   with:
      #     command: install



    # steps:
    #   - uses: actions/checkout@v1
    #   - uses: ./action-a
    #     with:
    #       MY_NAME: "Mona v${GITHUB_REF##*/}"